version: 1
services:
  - type: web
    name: bloom-africa-app
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: BLOOM_DB_HOST
        value: "127.0.0.1"
      - key: BLOOM_DB_NAME
        value: "bloom_africa"
      - key: BLOOM_DB_USER
        value: "root"
      - key: BLOOM_DB_PASS
        value: "bloom_root_pass"
      - key: BLOOM_DB_PORT
        value: "3306"
